- name: create the caralink-folder
  file:
    path: /user/korrav2/carelink_conf
    state: directory 
- name: create the carelink-stage1.minimed_conf_folder
  file:
     path: /user/korrav2/carelink-stage1.minimed_conf
     state: directory
- name: backup of httpd configurations
  command: export CARELINK_HOME=`find / -name carelink_conf*`
  command: false | cp -i $CARELINK_HOME /user/korrav2/carelink_conf 2>/dev/null
- name: backup of httpd configurations
  command: export CARELINK_STAGE_HOME=`find / -name carelink-stage1.minimed_conf*`
  command: false | cp -i $CARELINK_STAGE_HOME /user/korrav2/carelink-stage1.minimed_conf 2>/dev/null
