---
- hosts: staging
  become_user: korrav2
  become: yes
  gather_facts: false
  roles:
     - apache_update
     - apache_start
     - apache_stop
     - perforce_pull
     - perforce_push
     - backup
